services:
  huh.news.listener.insert_tags:
    class: HeimrichHannot\NewsBundle\EventListener\InsertTagsListener
    public: true
    arguments:
      - "@contao.framework"
  huh.news.listener.searchable_pages:
    class: HeimrichHannot\NewsBundle\EventListener\SearchablePagesListener
    public: true
    arguments:
      - "@contao.framework"
