services:
    heimrichhannot_news.listener.tag_manager:
        class: HeimrichHannot\NewsBundle\EventListener\TagManagerListener
        arguments:
            - "@codefog_tags.manager_registry"
    heimrichhannot_news.listener.backend.tl_news:
        class: HeimrichHannot\NewsBundle\EventListener\Backend\NewsListener