parameters:
    hh.newsbundle.news-feed-count: 20

services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

        HeimrichHannot\NewsBundle\Component\FeedSourceInterface:
            tags: [news-bundle.feed_source]

    app.news_tags_manager:
        class: HeimrichHannot\NewsBundle\Manager\NewsTagManager
        arguments:
            - "@contao.framework"
            - "tl_news"
            - "tags"
        tags:
            - { name: codefog_tags.manager, alias: app.news }

    hh.news-bundle.news_feed_generator:
        class: HeimrichHannot\NewsBundle\Component\NewsFeedGenerator
        arguments:
            - ['%hh.newsbundle.news-feed-count%']

    hh.news-bundle.news_feed_tag_source:
        class: HeimrichHannot\NewsBundle\Component\TagFeedSource