services:
    _defaults:
        public: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    huh.news.news_tags_manager:
        class: Codefog\TagsBundle\Manager\DefaultManager
        arguments:
            - "@contao.framework"
            - "tl_news"
            - "tags"
        tags:
            - { name: codefog_tags.manager, alias: app.news }

    huh.news.listener.callback.news:
      class: HeimrichHannot\NewsBundle\EventListener\NewsCallbackListener
      arguments: ["@contao.framework"]

    huh.news.backend.news:
        class: HeimrichHannot\NewsBundle\Backend\News
        arguments:
          - "@contao.framework"

    huh.news.backend.news_archive:
        class: HeimrichHannot\NewsBundle\Backend\NewsArchive
        arguments:
          - "@contao.framework"

    HeimrichHannot\NewsBundle\ConfigElementType\NewsPlayerElementType:
        tags: ['huh.reader.config_element_type']
        autowire: true
        public: false