services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    app.news_tags_manager:
        class: HeimrichHannot\NewsBundle\Manager\NewsTagManager
        arguments:
            - "@contao.framework"
            - "tl_news"
            - "tags"
        tags:
            - { name: codefog_tags.manager, alias: app.news }

    hh.news-bundle.news_feed_generator:
        class: HeimrichHannot\NewsBundle\Component\NewsFeedGenerator

    hh.news-bundle.news_feed_tag_source:
        class: HeimrichHannot\NewsBundle\Component\TagFeedSource
        tags: [news-bundle.feed_source, hh.newsalert.topic_source]

    hh.news-bundle.category_helper:
        class: HeimrichHannot\NewsBundle\Services\CategoryHelper