services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    huh.news.news_tags_manager:
        class: Codefog\TagsBundle\Manager\DefaultManager
        arguments:
            - "@contao.framework"
            - "tl_news"
            - "tags"
        tags:
            - { name: codefog_tags.manager, alias: app.news }

    huh.news.listener.callback.news:
      class: HeimrichHannot\NewsBundle\EventListener\NewsCallbackListener
      arguments: ["@contao.framework"]
    huh.news.backend.tl_news:
        class: HeimrichHannot\NewsBundle\Backend\News